fix: tar grpcurl permissions
https://github.com/nicolaka/netshoot/pull/158

grpcurl tar includes some wild UID/GID numbers that can't map to subuid/subgid.
```
2024-04-04 09:48:12 (10.9 MB/s) - '/tmp/grpcurl.tar.gz' saved [7706522/7706522]

tar: LICENSE: Cannot change ownership to uid 708061865, gid 708061865: Invalid argument
tar: grpcurl: Cannot change ownership to uid 708061865, gid 708061865: Invalid argument
tar: Exiting with failure status due to previous errors
chown: cannot access '/tmp/grpcurl': No such file or directory
Error: building at STEP "RUN /tmp/fetch_binaries.sh": while running runtime: exit status 1
```